<?php

/**
 * [BEGIN_COT_EXT]
 * Hooks=mavatars.show.tags
 * [END_COT_EXT]
 */
/**
 * plugin relatedpages for Cotonti Siena
 * 
 * @package relatedpages
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL.');

require_once cot_incfile('relatedpages', 'plug');
$pageid = cot_import('pageid', 'G', 'INT');
$cat = cot_import('cat', 'G', 'TXT');

$rmavatar = new related_mavatar('page', $cat, $pageid);
$rmavatars_tags = $rmavatar->generate_mavatars_tags();



//cot_print('page', $cat, $page, $rmavatars_tags);

$t->assign('RELATEDMAVATAR',$rmavatars_tags);
$t->assign('RELATEDMAVATARCOUNT', count($rmavatars_tags));
?>