<?php

/** 
 * [BEGIN_COT_EXT]
 * Hooks=page.edit.delete.done
 * [END_COT_EXT]
 */
 
/**
 * plugin addcatmaterial for Cotonti Siena
 * 
 * @package addcatmaterial
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL.');

require_once cot_incfile('relatedpages', 'plug');
cot_delete_ralatedpages($id);

?>