<?php

/**
 * [BEGIN_COT_EXT]
 * Code=relatedpages
 * Name=Related pages
 * Category=misc-ext
 * Description=Add related pages for page
 * Version=1.0.0
 * Date=2012-06-22
 * Author=esclkm
 * Auth_guests=R
 * Lock_guests=12345A
 * Auth_members=RW
 * [END_COT_EXT]
 * 
 * [BEGIN_COT_EXT_CONFIG]
 * infocat=03:string::polzn:Категория инфо страниц
 * [END_COT_EXT_CONFIG]
 *  * count=04:string::2:Количество
 * sort=05:select:title,rand:rand:Сортировка
 *  */

/**
 * plugin addcatmaterial for Cotonti Siena
 * 
 * @package addcatmaterial
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL');
