<?php

/**
 * [BEGIN_COT_EXT]
 * Hooks=page.tags
 * [END_COT_EXT]
 */
/**
 * plugin relatedpages for Cotonti Siena
 * 
 * @package relatedpages
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL.');

require_once cot_incfile('relatedpages', 'plug');

if ($t->hasTag('RELATEDPAGES'))
{
	$t->assign('RELATEDPAGES', cot_getrelatedpages($pag['page_id'], 'right'));
}
if ($t->hasTag('RELATEDPAGES_LEFT'))
{
	$t->assign('RELATEDPAGES_LEFT', cot_getrelatedpages($pag['page_id'], 'left'));
}

$mavatar = new related_mavatar('page', $pag['page_cat'], $pag['page_id']);
$mavatars_tags = $mavatar->generate_mavatars_tags();

$t->assign('RELATEDMAVATAR',$mavatars_tags);
$t->assign('RELATEDMAVATARCOUNT', count($mavatars_tags));
?>